version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: url-shortener-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - url-network

  app:
    build: .
    container_name: url-shortener-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
        PORT: ${PORT}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        MONGO_URL: ${MONGO_URL}
        
    depends_on:
      - redis
    networks:
      - url-network

volumes:
  redis-data:
    driver: local

networks:
  url-network:
    driver: bridge